spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://db:5432/userdb
    username: cartly
    password: cartly123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 9090


